// docs.go
// This file is used for Swagger API documentation.
// It should be located in the same package as your main application.

package main

import _ "github.com/l-orlov/simple-todo-list/server/docs" // docs is generated by Swag CLI, we need import it

// @title Your API Title
// @version 1.0
// @description Your API description. You can use Markdown here.
// @host localhost:8080
// @BasePath /api/v1
func main() {
	// This function is only for the purpose of godoc and should be empty.
}
