basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      description: This endpoint provides a short welcome message
      produces:
      - text/plain
      responses:
        "200":
          description: welcome
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "403":
          description: forbidden
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Welcome endpoint
securityDefinitions:
  Bearer:
    description: Bearer {YOUR_TOKEN}
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
