basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      description: This endpoint provides a short welcome message
      produces:
      - text/plain
      responses:
        "200":
          description: welcome
          schema:
            type: string
      security:
      - Bearer: []
      summary: Welcome endpoint
securityDefinitions:
  Bearer:
    description: Bearer {YOUR_TOKEN}
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
